### ISSUE TITLE
Python Mode won't run sketches in 4.0b6

### ISSUE THREAD

**Issue by tabreturn** [benfry/processing4#409]
## Description
Python Mode worked in 4.0b5, but won't run sketches in 4.0b6

## Expected Behavior
Python Mode Sketches won't run. Instead I get this error in the console (truncated here) --
```
Exception in thread "AWT-EventQueue-0" java.lang.NoSuchMethodError: 'java.lang.String processing.app.Sketch.getMainProgram()'
	at jycessing.mode.run.PdeSketch.<init>(PdeSketch.java:55)
	at jycessing.mode.PyEditor.runSketch(PyEditor.java:348)
	at jycessing.mode.PyEditor.handleRun(PyEditor.java:369)
	at jycessing.mode.PyToolbar.handleRun(PyToolbar.java:22)
	at processing.app.ui.EditorToolbar$1.actionPerformed(EditorToolbar.java:135)
	...
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

## Steps to Reproduce
1. Install Python Mode in 4.0b6
2. Attempt to run a sketch

## Your Environment
* Processing version: 4.0b6
* Operating System and OS version: Linux Mint 20.3 Cinnamon

## Possible Causes / Solutions
Note sure of the cause. For now, Processing Python Mode users could use 4.0b5 or 3.5.4

**Comment by benfry** [comment]
Nuts; ok… that's due to detaching sketch name and the name of the first tab. Didn't realize Python Mode was using that method.

**Comment by benfry** [comment]
Added a fix for beta 7; in the meantime you can also just build from the source.

**Comment by Rauschii** [comment]
> Added a fix for beta 7; in the meantime you can also just build from the source.

Hi, i know it is unusual to ask here but I cannot contact you otherwise. 
 I don' t want to stress but I am using Processing for my university course and our semester starts today. Could you let me know when Version 7 is coming? Thank you very much for any hint in advance.

**Comment by benfry** [comment]
I'd like to get something out as soon as possible (today? this week?) but it's just a matter of when I can get some spare time to make it happen. Beta 5 should also work fine (still on the GitHub releases page) in case that's an option for you.

**Comment by tabreturn** [comment]
https://github.com/processing/processing4/releases/tag/processing-1280-4.0b5

**Comment by Rauschii** [comment]
Thank you both!!! @benfry  and @tabreturn

**Comment by benfry** [comment]
Beta 7, which has the fixes, has been up for 3 weeks: https://github.com/processing/processing4/releases

If there are problems with beta 7, I've not seen any reports yet.
